spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.154:3306/jpa?serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate:
#    更新或者创建数据结构
      ddl-auto: update
    show-sql: true