server:
  port: 8079
spring:
  profiles:
    active: dev
---
server:
  port: 8083
spring:
  profiles: dev
---
server:
  port: 8084
spring:
  profiles: prod
---
#person:
#    age: ${random.int}
#    boss: false
#    birth: 2017/12/12
#    maps: {k1:v1,k2:v2}
#    lists:
#        - 1
#        - 2
#    dog:
#        name: ${person.lastName:hello_}阿黄
#        age: 3
#    name: 张三${random.uuid}